import pygame

from pygame.locals import (
    K_UP,
    K_DOWN,
    K_LEFT,
    K_RIGHT,
    K_RETURN,
    K_SPACE,
    K_ESCAPE,
    K_q,
    KEYDOWN,
    QUIT,
    K_TAB,
    K_0,
    K_1,
    K_2,
    K_p
)

# Arena Parameters
SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1600

# Players
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_SCALE = 2

PLAYER_WALKING = 0
PLAYER_TRANSFORMING = 1
PLAYER_SHOOTING = 2

WEIGHT_FACTOR = 0.2

INVENTORY_SIZE = 5

# Team
team_boundaries = {
        0: {
            "top": 0,
            "bottom": 736 - PLAYER_HEIGHT*PLAYER_SCALE
        },
        1: {
            "top": 853 + PLAYER_HEIGHT*PLAYER_SCALE,
            "bottom": SCREEN_HEIGHT
        }
    }

# Veggies
VEGGIE_WIDTH = 18
VEGGIE_HEIGHT = 20
VEGGIE_SCALE = 1

MAX_VEGGIES = 5

TOMATO_DAMAGE = 2
PEACH_DAMAGE = 4
CARROT_DAMAGE = 6
POTATO_DAMAGE = 8
PUMPKIN_DAMAGE = 15
MILK_POWER = 1
RUBY_POWER = 10
VEGGIE_VELOCITY = 10

# Weapons
TROLLY_VELOCITY = (0.5,0)
TROLLY_WIDTH = 48
TROLLY_HEIGHT = 32
WEAPON_HEIGHT = 32
WEAPON_WIDTH = 32
WEAPON_SCALE = 1

# Maps
SPRING = 0
FALL = 1
WINTER = 2

# Shots
SHOT_WIDTH = 32
SHOT_HEIGHT = 32
SHOT_SCALE = 1

# Bases
BASE_WIDTH = 80
BASE_HEIGHT = 80
BASE_SCALE = 1

# Game Parameters
TEAM0_SPAWN = (SCREEN_WIDTH/2, SCREEN_HEIGHT*(1/5))
TEAM1_SPAWN = (SCREEN_WIDTH/2, SCREEN_HEIGHT*(4/5))

# TODO: Deprecate the variables below?

PLAYER_ENGINEER = 3
PLAYER_FARMER = 4
PLAYER_SOLDIER = 5
PLAYER_TRAVELER = 6

GAME_ON = 1
