# Arena Parameters
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 20
SLINGSHOT_WIDTH = 50
SLINGSHOT_HEIGHT = 50
SHOT_WIDTH = 5
SHOT_HEIGHT = 10

# Veggie damage
VEGGIE_POTATO = 5
VEGGIE_CARROT = 7
VEGGIE_CABBAGE = 10
VEGGIE_PUMPKIN = 15

# Veggie weights

# Player State
PLAYER_WALKING = 0
PLAYER_HARVESTING = 1
PLAYER_SHOOTING = 2

# Player Weight
WEIGHT_FACTOR = 0.2

# Player Role
PLAYER_ENGINEER = 3
PLAYER_FARMER = 4
PLAYER_SOLDIER = 5
PLAYER_TRAVELER = 6

# Game object team assignment
TEAM1 = 1
TEAM2 = 2

# Game Flow
GAME_ON = 1